# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: JobA
        steps:
          - script: |
              echo Sample Line1 in JobA
              echo Sample Line2 in JobA
            displayName: "This is Job A Text"
      - job: JobB
        steps:
          - script: |
              echo Sample Line1 in JobB
              echo Sample Line2 in JobB
            displayName: "This is Job B Text"                      
